name1 = ("jack")
addy = ("n37wr13")
print (name1)
import time
time.sleep (1)
print (addy)
time.sleep (1)
print (400)
time.sleep (1)
print("###### ###### ######")
print("    ## ##     ##")
print("###### ###### ######")
print("    ## ##  ##     ##")
print("###### ###### ######")